# See HAKCPolicyProcessConfig in llvm-project/llvm/utils/hakc/hakc/HAKCPolicyServer.py
{
  "backing_policy_config": {
    # See SupportedBackingStore in llvm-project/llvm/utils/hakc/hakc/HAKCPolicyServer.py
    "type": "kuzu",
    "path": "<path/to/kuzu/database/dir>",
    "default_compartment": 0,
    "default_division": 0
  },
  "socket_path": "hakc-dag-analysis/db-socket",
  "reuse_path": true,
  "test-mode": false,
  "server_timeout": 100,
  "get-compartment-by-id-endpoint": "get-compartment-by-id",
  "get-division-by-id-endpoint": "get-division-by-id",
  "get-division-from-symbol-endpoint": "get-division-from-symbol",
  "get-valid-targets-from-compartment-id-endpoint": "get-valid-targets-from-compartment-id"
}
