# CI framework for HAKC repo

variables:
  NEXT_BRANCH: '/^*-next/'
  DEV_BRANCH: '/^*-dev/'
  EXT_BRANCH: '/^ext-*/'
  MAIN_BRANCH: 'hakc'
  STAGING_BRANCH: 'hakc-staging'
  DAG_FILE_PATH: 'dag-output'
  RPI_IMG_FILE: '/data/gitlab-runner/rpi.img'
  BUILD_PROCESSORS: 96
  LLVM_BUILD_DIR: $CI_PROJECT_DIR/cmake-llvm-build-release
  PYTHON_VENV_DIR: $CI_PROJECT_DIR/python/venv
  LLVM_INSTALL_DIR: $CI_PROJECT_DIR/deploy/llvm-install
  PYTHON_DEPLOY_DIR: $CI_PROJECT_DIR/deploy/python
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: none

# Overview of stages (all jobs for a given stage run parallel before the next stage)
# check - check that repo is in logical functioning manner (e.g. submodules match)
# build - build everything (we may need to break this down for building DAGs)
# test - Test different setups

.llvm_settings:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_PATHS: llvm-project
    TEST_SOCKET_PATH: '/tmp/hakc-sockets'
  rules:
    - changes:
        paths:
          - .git/modules/llvm-project/refs/heads/$CI_COMMIT_BRANCH
          - .ci/build_llvm-job.yml
          - .gitlab-ci.yml

stages:
  - build_llvm
  - run_llvm_tests
  - deploy_llvm

include:
  - '.ci/build_llvm-job.yml'
  - '.ci/deploy_llvm-job.yml'
  - '.ci/run_llvm_tests-jobs.yml'
