SYSTEMINFO:
  ARCH:             X86
  PLATFORM:         CheriBSD
  METHODS:
    - NAME:         GetNoTransferFunctions
      FUNCTIONS:
        - "mi_startup"
        - "init_main"
        - "g_load_class"
        - "cheri_init_capabilities"
        - "create_pagetables"
    - NAME:         GetSeparateNamespacePaths
      FUNCTIONS:
        - "sys/arm64/arm64/elf_machdep.c"
        - "sys/arm64/arm64/machdep.c"
        - "sys/arm64/arm64/machdep_boot.c"
        - "sys/contrib/libfdt/fdt.c"
    - NAME:         GetHAKCSourcePaths
      FUNCTIONS:
        - "sys/hakc/hakc.c"
    - NAME:         GetSafeTransitionFunctions
      FUNCTIONS:
        - "generic_bs_r_1"
        - "generic_bs_r_2"
        - "generic_bs_r_4"
        - "generic_bs_r_8"
        - "generic_bs_rm_1"
        - "generic_bs_rm_2"
        - "generic_bs_rm_4"
        - "generic_bs_rm_8"
        - "generic_bs_rr_1"
        - "generic_bs_rr_2"
        - "generic_bs_rr_4"
        - "generic_bs_rr_8"
        - "generic_bs_w_1"
        - "generic_bs_w_2"
        - "generic_bs_w_4"
        - "generic_bs_w_8"
        - "generic_bs_wm_1"
        - "generic_bs_wm_2"
        - "generic_bs_wm_4"
        - "generic_bs_wm_8"
        - "generic_bs_wr_1"
        - "generic_bs_wr_2"
        - "generic_bs_wr_4"
        - "generic_bs_wr_8"
        - "generic_bs_peek_1"
        - "generic_bs_peek_2"
        - "generic_bs_peek_4"
        - "generic_bs_peek_8"
        - "generic_bs_poke_1"
        - "generic_bs_poke_2"
        - "generic_bs_poke_4"
        - "generic_bs_poke_8"
        - "arm64_dic_idc_icache_sync_range"
        - "arm64_aliasing_icache_sync_range"
        - "pagezero_cache"
        - "pagezero_simple"
        - "casueword32_lse"
        - "casueword32_llsc"
        - "casueword_lse"
        - "casueword_llsc"
        - "arm_smccc_hvc"
        - "arm_smccc_smc"
        - "copyin"
        - "copyout"
        - "mpentry"
        - "generic_bs_fault"
        - "fork_trampoline"
        - "strlen"
        - "strnlen"
        - "memcpy"
        - "memcmp"
        - "strcmp"
        - "strncmp"
        - "memchr"
        - "memmove"
        - "strchr"
        - "strrchr"
        - "memset"
    - NAME:          GetIgnoredTypes
      FUNCTIONS:
        - "struct.rwlock"
        - "struct.sx"
        - "struct.lock"
    - NAME:          GetFinalAllocaDef
        - "cheri_cap_bounds_set"
        - "cheri_cap_bounds_set_exact"
    - NAME:          GetIntrinsicsNeedingAuthenticatedArgs
        - "cheri_cap_bounds_set"
        - "cheri_cap_bounds_set_exact"
        - "cheri_cap_address_get"
        - "cheri_cap_address_set"
        - "cheri_cap_sealed_get"
    - NAME:          GetInstrinsicsToSkip
        - "cheri_bounded_stack_cap"
        - "cheri_bounded_stack_cap_dynamic"
        - "cheri_cap_address_get"
        - "cheri_cap_address_set"
        - "cheri_cap_base_get"
        - "cheri_cap_bounds_set"
        - "cheri_cap_bounds_set_exact"
        - "cheri_cap_build"
        - "cheri_cap_conditional_seal"
        - "cheri_cap_copy_from_high"
        - "cheri_cap_copy_to_high"
        - "cheri_cap_diff"
        - "cheri_cap_equal_exact"
        - "cheri_cap_flags_get"
        - "cheri_cap_flags_set"
        - "cheri_cap_from_pointer"
        - "cheri_cap_from_pointer_nonnull_zero"
        - "cheri_cap_length_get"
        - "cheri_cap_load_tags"
        - "cheri_cap_offset_get"
        - "cheri_cap_offset_set"
        - "cheri_cap_perms_and"
        - "cheri_cap_perms_check"
        - "cheri_cap_perms_get"
        - "cheri_cap_sealed_get"
        - "cheri_cap_seal"
        - "cheri_cap_seal_entry"
        - "cheri_cap_subset_test"
        - "cheri_cap_tag_clear"
        - "cheri_cap_tag_get"
        - "cheri_cap_to_pointer"
        - "cheri_cap_type_check"
        - "cheri_cap_type_copy"
        - "cheri_cap_type_get"
        - "cheri_cap_unseal"
        - "cheri_ddc_get"
        - "cheri_pcc_get"
        - "cheri_representable_alignment_mask"
        - "cheri_round_representable_length"
        - "cheri_stack_cap_get"
    - NAME:          IDsToIgnore
        - "cheri_cap_bounds_set"
        - "cheri_cap_bounds_set_exact"
