{
  "backing_store": {
    "type": "null",
    # "type": "yaml", 
    # "path": "@HAKC_BACKING_STORE@",
    # "default_compartment": 0,
    # "default_division": 0
  },
  "reuse_path": true,
  "socket_path": "@PWD@/hakc-socket",
  "server_timeout": 10
}
