{
  "backing_store": {
    "type": "json",
    "path": "/home/al32163/hakc/HAKC_CURR/python/analysis/backing.json",
    "default_comparment" : 0,
    "default_division" : 0
  },
  "reuse_path": true,
  "socket_path": "hakc-socket"
}
