SYSTEMINFO:
  ARCH:             X86
  PLATFORM:         Linux
  NoTransferFunctions:
    - "clear_page_orig"
    - "clear_page_rep"
    - "clear_page_erms"
    - "copy_user_generic_unrolled"
    - "copy_user_generic_string"
    - "copy_user_enhanced_fast_string"
    - "asm_sysvec_xen_hvm_callback"
    - "sha256_transform_avx"
    - "sha256_transform_ssse3"
    - "sha256_transform_avx"
    - "sha256_transform_rorx"
    - "sha256_ni_transform"
    - "__bpf_call_base"
    - "ftrace_stub"
    - "ftrace_stub_graph"
    - "ftrace_call"
    - "parse_memtest"
    - "__stack_chk_fail"
    - "is_vmalloc_addr"
    - "page_to_phys"
    - "vmalloc_to_page"
    - "virt_to_pfn"
    - "cleanup_module"
    - "raid6_int4_xor_syndrome"
    - "raid6_int1_gen_syndrome"
    - "raid6_int2_xor_syndrome"
    - "raid6_int8_gen_syndrome"
    - "raid6_int4_gen_syndrome"
    - "raid6_int2_gen_syndrome"
    - "raid6_int8_xor_syndrome"
    - "raid6_int1_xor_syndrome"
    - NAME:         GetSeparateNamespacePaths
      FUNCTIONS:
        - "arch/x86/kvm/emulate.c"
        - "arch/x86/kernel/idt.c"
        - "arch/x86/kernel/irq.c"
        - "arch/x86/kernel/ftrace.c"
        - "arch/x86/kernel/machine_kexec_64.c"
        - "arch/x86/kernel/module.c"
        - "arch/x86/net/bpf_jit_comp.c"
        - "arch/x86/kernel/x86_init.c"
        - "arch/x86/kernel/pci-swiotlb.c"
        - "arch/x86/kernel/acpi/boot.c"
        - "arch/x86/xen/apic.c"
        - "arch/x86/xen/efi.c"
        - "arch/x86/xen/enlighten_hvm.c"
        - "arch/x86/xen/enlighten.c"
        - "arch/x86/xen/enlighten_pv.c"
        - "arch/x86/xen/grant-table.c"
        - "arch/x86/xen/irq.c"
        - "arch/x86/xen/mmu_hvm.c"
        - "arch/x86/xen/mmu.c"
        - "arch/x86/xen/mmu_pv.c"
        - "arch/x86/xen/multicalls.c"
        - "arch/x86/xen/p2m.c"
        - "arch/x86/xen/pci-swiotlb-xen.c"
        - "arch/x86/xen/platform-pci-unplug.c"
        - "arch/x86/xen/pmu.c"
        - "arch/x86/xen/setup.c"
        - "arch/x86/xen/smp_hvm.c"
        - "arch/x86/xen/smp.c"
        - "arch/x86/xen/smp_pv.c"
        - "arch/x86/xen/suspend_hvm.c"
        - "arch/x86/xen/suspend.c"
        - "arch/x86/xen/suspend_pv.c"
        - "arch/x86/xen/time.c"
        - "arch/x86/xen/trace.c"
        - "arch/x86/xen/vga.c"
        - "arch/x86/xen/xen-asm.c"
        - "arch/x86/kernel/paravirt.c"
        - "arch/x86/kernel/kvm.c"
        - "arch/x86/kernel/cpu/vmware.c"
        - "fs/readdir.c"
        - "mm/maccess.c"
        - "net/core/scm.c"
        - "mm/gup.c"
        - "arch/x86/kernel/signal_64.c"
        - "arch/x86/kvm/x86.c"
        - "kernel/rseq.c"
        - "net/core/filter.c"
        - "arch/x86/kernel/signal.c"
        - "kernel/entry/common.c"
        - "drivers/firmware/efi/libstub/fdt.c"
        - "lib/idr.c"
        - "lib/xarray.c"
    - NAME:         GetHAKCSourcePaths
      FUNCTIONS:
        - "arch/x86/kernel/hakc/hakc_ni.c"
        - "arch/x86/kernel/hakc/hakc.c"
        - "arch/x86/kernel/hakc/hakc_btree.c"
        - "arch/x86/kernel/hakc/hakc_memory.c"
        - "kernel/hakc/hakc_common.c"
        - "kernel/hakc/hakc_noarch_tag_btree.c"
        - "kernel/hakc/hakc_noarch_tag_memory.c"
        - "fs/fuse/transfer.c"
        - "drivers/usb/storage/transfer.c"
        # - "/home/al32163/hakc/HAKC/HAKC-pass/tests/llvm_tests/tests/hakc-test0.c"
    - NAME:         GetSafeTransitionFunctions
      FUNCTIONS:
        - "clear_page"
        - "kmemdup"
        - "__memcpy"
        - "__pi_memcmp"
        - "__pi_strcmp"
        - "bcmp"
        - "__arch_copy_from_user"
        - "__memset"
        - "memchr_inv"
        - "__arch_copy_to_user"
        - "xas_load"
        - "xas_find_marked"
        - "xa_head"
        - "crc32_le"
        - "__crc32c_le"
        - "cpu_switch_to"
        - "__pi_clear_page"
        - "clear_page"
        - "__clear_page"
        - "__pi_copy_page"
        - "copy_page"
        - "__copy_page"
        - "__pi_memchr"
        - "memchr"
        - "__memchr"
        - "__pi_memcpy"
        - "memcpy"
        - "__memcpy"
        - "__pi_memmove"
        - "memmove"
        - "__memmove"
        - "__pi_memset"
        - "memset"
        - "__memset"
        - "__pi_strlen"
        - "strlen"
        - "memcmp"
        - "strcmp"
        - "memchr"
        - "strchr"
        - "__strlen"
        - "__pi_strncmp"
        - "strncmp"
        - "__strncmp"
        - "__pi_strnlen"
        - "strnlen"
        - "__strnlen"
        - "__pi_strrchr"
        - "strrchr"
        - "__strrchr"
        - "__arch_clear_user"
        - "__ashlti3"
        - "__ashrti3"
        - "__lshrti3"
    - NAME:          GetIgnoredTypes
      FUNCTIONS:
        - "struct.list_head"
        - "struct.proto"
        - "struct.atomic64_s"
        - "struct.atomic_s"
    - NAME:          GetIgnoredGlobals
      FUNCTIONS:
        - "kmalloc_caches"
    - NAME:         GetKernelAllocationSizeMap
      FUNCTIONS:
        - "kmalloc|simpleArgumentSize|0"
        - "kzalloc|simpleArgumentSize|0"
        - "__kmalloc|simpleArgumentSize|0"
        - "neigh_parms_alloc|simpleStaticSize|144"
        - "nlmsg_new|staticPlusArgument|64|0"
        - "kmemdup|simpleArgumentSize|1"
        - "__alloc_percpu|simpleArgumentSize|0"
        - "__alloc_percpu_gfp|simpleArgumentSize|0"
        - "kmalloc_array|multiplyTwoArguments|0|1"
        - "kcalloc|multiplyTwoArguments|0|1"
        - "sk_alloc|simpleStaticSize|64"
        - "__alloc_skb|simpleArgumentSize|0"
        - "kmem_cache_zalloc|simpleArgumentSize|0"
        - "nla_memdup|simpleStaticSize|64"
        - "kzalloc_node|simpleArgumentSize|0"
        - "fib_rules_register|simpleStaticSize|256"
        - "nla_strdup|simpleStaticSize|64"
        - "kvmalloc|simpleArgumentSize|0"
        - "kvmalloc_array|multiplyTwoArguments|0|1"
        - "kvzalloc|simpleArgumentSize|0"
        - "kmem_cache_alloc|argumentGEP|0|1"
        - "kmem_cache_alloc_trace|simpleArgumentSize|2"
        - "create_workqueue|simpleStaticSize|320"
        - "device_create|simpleStaticSize|768"
        - "__class_create|simpleStaticSize|120"
    - NAME:         functionIsTransferCandidate
      FUNCTIONS:
        - "__SCT"
    - NAME:         FunctionNeedsAnalysis
      FUNCTIONS:
        - "static_branch_"
    - NAME:         pointerShouldBeChecked
      FUNCTIONS:
        - "hakc_safe_ptr"
