SYSTEMINFO:
  ARCH:             armv9
  PLATFORM:         Linux
  METHODS:
    - NAME:         GetNoTransferFunctions
      FUNCTIONS:
        - "__bpf_call_base"
        - "ftrace_stub"
        - "ftrace_stub_graph"
        - "ftrace_call"
        - "parse_memtest"
        - "__stack_chk_fail"
        - "is_vmalloc_addr"
        - "page_to_phys"
        - "vmalloc_to_page"
        - "virt_to_pfn"
        - "raid6_int4_xor_syndrome"
        - "raid6_int1_gen_syndrome"
        - "raid6_int2_xor_syndrome"
        - "raid6_int8_gen_syndrome"
        - "raid6_int4_gen_syndrome"
        - "raid6_int2_gen_syndrome"
        - "raid6_int8_xor_syndrome"
        - "raid6_int1_xor_syndrome"
        - "aesbs_xts_encrypt"
        - "aesbs_xts_decrypt"
        - "_cpu_resume"
        - "kretprobe_trampoline"
    - NAME:         GetSeparateNamespacePaths
      FUNCTIONS:
        - "arch/arm64/kvm/hyp/"
        - "arch/arm64/kernel/vdso/"
    - NAME:         GetHAKCSourcePaths
      FUNCTIONS:
        - "arch/arm64/kernel/hakc/armv9/hakc_pac_mte.c"
        - "arch/arm64/kernel/hakc/armv9/hakc.c"
    - NAME:         GetSafeTransitionFunctions
      FUNCTIONS:
        - "clear_page"
        - "kmemdup"
        - "__memcpy"
        - "__pi_memcmp"
        - "__pi_strcmp"
        - "bcmp"
        - "__arch_copy_from_user"
        - "__memset"
        - "memchr_inv"
        - "__arch_copy_to_user"
        - "xas_load"
        - "xas_find_marked"
        - "xa_head"
        - "crc32_le"
        - "__crc32c_le"
        - "cpu_switch_to"
        - "__pi_clear_page"
        - "clear_page"
        - "__clear_page"
        - "__pi_copy_page"
        - "copy_page"
        - "__copy_page"
        - "__pi_memchr"
        - "memchr"
        - "__memchr"
        - "__pi_memcpy"
        - "memcpy"
        - "__memcpy"
        - "__pi_memmove"
        - "memmove"
        - "__memmove"
        - "__pi_memset"
        - "memset"
        - "__memset"
        - "__pi_strlen"
        - "strlen"
        - "__strlen"
        - "__pi_strncmp"
        - "strncmp"
        - "__strncmp"
        - "__pi_strnlen"
        - "strnlen"
        - "__strnlen"
        - "__pi_strrchr"
        - "strrchr"
        - "__strrchr"
        - "__arch_clear_user"
        - "__ashlti3"
        - "__ashrti3"
        - "__lshrti3"
        - "memcmp"
        - "strcmp"
        - "strchr"
        - "memset"
    - NAME:          GetIgnoredTypes
      FUNCTIONS:
        - "struct.list_head"
        - "struct.proto"
        - "struct.atomic64_s"
        - "struct.atomic_s"
    - NAME:          GetIgnoredGlobals
      FUNCTIONS:
        - "kmalloc_caches"
