!HAKCAdjustments
add-kernel-division: true
compartmentalize:
  - !HAKCAdjustmentOnPath
    path: 'linux/drivers/rosdemo/rosdemo\-leaker.c'
    division_id: 8
    compartment_id: 2048
  - !HAKCAdjustmentOnPath
    path: 'linux/drivers/rosdemo/rosdemo\-consumer.c'
    division_id: 16
    compartment_id: 1024
  - !HAKCAdjustmentOnSymbol
    path: 'linux/drivers/rosdemo/rosdemo\-consumer.c'
    symbol: 'rosdemo_consumer_exit'
    division_id: 32
    compartment_id: 1024
