!HAKCAdjustments
no-enforcement-compartment: true
adjustments:
  - !HAKCCompartmentAdjustment
    path: 'linux/drivers/rosdemo/rosdemo\-leaker.c'
    division-id: 8
    compartment-id: 2048
  - !HAKCCompartmentAdjustment
    path: 'linux/drivers/rosdemo/rosdemo\-consumer.c'
    division-id: 15
    compartment-id: 1024
