name: Analyze-and-Build-HAKC-Kernel
env:
  http_proxy: "http://llproxy.llan.ll.mit.edu:8080"
  https_proxy: "http://llproxy.llan.ll.mit.edu:8080"
  no_proxy: ".llan.ll.mit.edu,localhost,127.0.0.1,172.25.4.225,172.16.0.0/12,10.42.0.0/16,10.43.0.0/16"
  IMAGEID: "g53-hakc-linux"
  REPOURL: "ett-jfrog.llan.ll.mit.edu"
  REPOID: "g0553-docker-local"
  BUILD_DIR: "cmake-build-hakc-release"
  DEPS_TO_INSTALL: "ninja-build cmake busybox-static python3-venv qemu-system"
  VENV_DIR: "python/venv"
  LINUX_ARCH: "x86_64"

on:
  workflow_run:
    workflows: [ "Publish LLVM Image" ]
    types:
      - completed

jobs:
  BuildDAG:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ arc-runner-set-llcad-amdxl-prod ]
    container:
      image: ${{ env.REPOURL }}/${{ env.REPOID }}/${{ env.IMAGEID }}:amd64-${{ github.event.workflow_run.head_sha }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Install Dependencies
        shell: bash
        run: |
          set -euo pipefail
          chown -R root:root .
          apt update
          apt install -y $DEPS_TO_INSTALL
      - name: Configure Environment
        shell: bash
        run: |
          set -euo pipefail
          cmake --preset ci-linux-build
      - name: Generating DAG
        shell: bash
        run: |
          set -euo pipefail
          python3 -m venv $VENV_DIR
          source $VENV_DIR/bin/activate
          pip install -r llvm-project/llvm/utils/hakc/requirements.txt
          cmake --build $BUILD_DIR --target hakc-linux-$LINUX_ARCH-analysis
      - name: Upload DAG artifact
        uses: actions/upload-artifact@v4
        with:
          name: hakc-dag
          path: ${{ env.BUILD_DIR }}/linux/${{ env.LINUX_ARCH }}/hakc-db
  BuildHAKCKernel:
    runs-on: [ arc-runner-set-llcad-amdxl-prod ]
    container:
      image: ${{ env.REPOURL }}/${{ env.REPOID }}/${{ env.IMAGEID }}:amd64-${{ github.event.workflow_run.head_sha }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Install Dependencies
        shell: bash
        run: |
          set -euo pipefail
          chown -R root:root .
          apt update
          apt install -y $DEPS_TO_INSTALL
      - name: Configure Environment
        shell: bash
        run: |
          set -euo pipefail
          cmake --preset ci-linux-build
      - name: Download DAG artifact
        uses: actions/download-artifact@v4
        with:
          name: hakc-dag
          path: ${{ env.BUILD_DIR }}/linux/${{ env.LINUX_ARCH }}/hakc-db
      - name: Build HAKC Kernel
        shell: bash
        run: |
          set -euo pipefail
          cmake --build $BUILD_DIR --target hakc-linux-$LINUX_ARCH-enforcement
      - name: Build Userspace
        shell: bash
        run: |
          set -euo pipefail
          cmake --build $BUILD_DIR --target hakc-$LINUX_ARCH-userspace
      - name: Build & Push Image
        shell: bash
        env:
          jfrog_user: ${{ secrets.JFROG_USER }}
          jfrog_pass: ${{ secrets.JFROG_PASS }}
          COMMIT_TAG: "amd64-${{ github.sha }}"
          LATEST_TAG: "amd64-latest"
          INSTALL_DIR: "${{ env.BUILD_DIR }}/linux/${{ env.LINUX_ARCH }}"
        run: |
          set -euo pipefail
          envsubst < Dockerfile-linux.template > Dockerfile
          export _BUILDAH_STARTED_IN_USERNS=""
          export BUILDAH_ISOLATION=chroot

          buildah login -u "$jfrog_user" -p "$jfrog_pass" "$REPOURL"

          # Build with commit tag
          buildah bud  --storage-driver vfs -t "$REPOURL/$REPOID/$IMAGEID:$COMMIT_TAG" .
          buildah push --storage-driver vfs    "$REPOURL/$REPOID/$IMAGEID:$COMMIT_TAG"

          # Update amd64-latest as a moving pointer (optional but useful)
          buildah tag  --storage-driver vfs    "$REPOURL/$REPOID/$IMAGEID:$COMMIT_TAG" "$REPOURL/$REPOID/$IMAGEID:$LATEST_TAG"
          buildah push --storage-driver vfs    "$REPOURL/$REPOID/$IMAGEID:$LATEST_TAG"
